title: Don Knieriem  Web Developer
author: dknieriem
email: donald.knieriem@gmail.com
description: Philly | Web Dev | Gritty Fan
logo: face-trans.png
github_username: dknieriem
show_excerpts: true
theme: jekyll-theme-minimal